---
- hosts: all
  vars_files:
     - config/vars/php.yml
     - config/vars/xdebug.yml
     - config/vars/nginx.yml
     - config/vars/ssl.yml
     - config/vars/mysql.yml
  roles:
     - php
     - php-xdebug
     - ssl-certs
     - nginx
     - mysql
     - composer
     - redis
     - mongodb
