---
- src: https://github.com/geerlingguy/ansible-role-php.git
  version: master
  name: php

- src: https://github.com/geerlingguy/ansible-role-php-xdebug.git
  version: master
  name: php-xdebug

- src: https://github.com/jdauphant/ansible-role-ssl-certs.git
  version: master
  name: ssl-certs

