---
- src: https://github.com/geerlingguy/ansible-role-php.git
  version: master
  name: php

- src: https://github.com/geerlingguy/ansible-role-php-xdebug.git
  version: master
  name: php-xdebug

- src: https://github.com/jdauphant/ansible-role-ssl-certs.git
  version: master
  name: ssl-certs

- src: https://github.com/jdauphant/ansible-role-nginx.git
  version: master
  name: nginx

- src: https://github.com/geerlingguy/ansible-role-mysql.git
  version: master
  name: mysql

- src: https://github.com/geerlingguy/ansible-role-composer.git
  version: master
  name: composer

- src: https://github.com/DavidWittman/ansible-redis.git
  version: master
  name: redis

- src: https://github.com/UnderGreen/ansible-role-mongodb.git
  version: master
  name: mongodb

- src: https://github.com/geerlingguy/ansible-role-nodejs.git
  version: master
  name: nodejs
