---
- hosts: all
  vars_files:
     - config/vars/php.yml
     - config/vars/xdebug.yml
     - config/vars/nginx.yml
     - config/vars/mysql.yml
  roles:
     - role: php
     - role: php-xdebug
     - role: nginx
     - role: mysql
     - role: composer
